version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./startup.sh:/startup.sh
    entrypoint: [ "bash", "/startup.sh" ]
    restart: unless-stopped

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - ollama
    volumes:
      - webui_data:/app/backend/data
    restart: unless-stopped

  rag-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: rag-api
    ports:
      - "15674:15674"
    env_file:
      - .env
    volumes:
      - ./chroma_db:/app/chroma_db
      - ./repos:/app/repos
      - ./api_rag_agent.py:/app/api_rag_agent.py
      - ./requirements-api.txt:/app/requirements-api.txt
      - .env:/app/.env
    depends_on:
      - ollama
    restart: unless-stopped

volumes:
  ollama_data:
  webui_data:
